/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    // to do: index(325-383)
    //#region 主界面及序数等
    'Submit': '提交',
    'Cancel': '取消',
    'Welcome Back!': '欢迎回来！',
    'You\'ve loaded into Ordinal PRINGLES v0.3.3: The World\'s Purest Pringle\nEnjoy!': '目前序数品客的版本为v0.3.3：世界上最纯正的品客。享受游戏吧！',
    'Thanks!': '谢谢！',
    'Ordinals': '序数',
    'Markup': '增序',
    'Boosters': '提升器',
    'Collapse': '坍缩',
    'Achievements': '成就',
    'Settings': '设置',
    'Increase Successor by 1 (S': '使后继数增加1(S',
    'Maximize Ordinal (M': '最大化序数(M',
    //#endregion
    //#region 增序
    'Factors': '因子',
    'Base 2 is required to go further...': '想要前进，您需要达到底数2……',
    'Perform a Factor Shift': '因子变换',
    'Perform a Factor Shift (H': '因子变换(H',
    'Requires: ?????': '需：?????',
    'Performing a Factor Shift will reduce your Base by 1 and unlock a new Factor, but it will reset your Ordinal, Ordinal Powers, Factors, and Automation!': '进行因子变换后，底数将减少1，并解锁一个新的因子，但序数，序数幂，因子和自动点击器将重置！',
    'Yes, lets do this.': '继续，没问题。',
    'Are you certain?': '您确定了吗？',
    'This will perform a Collapse, which will reset EVERYTHING you\'ve done so far in exchange for three Cardinals. The next layer awaits....': '这将进行一次坍缩，重置目前为止的一切，但可以获得 3 个基数。更高的层次欢迎您光临……',
    'Not yet.': '现在还不急。',
    'To the beyond!': '出发吧！',
    'Insufficient Ordinal': '序数不足',
    'The End... for now!': '暂时……到达终点！',
    'Congratulations!': '恭喜！',
    'You\'ve Factor Boosted 30 times! Something new is right around the corner, but these last 4 Boosts will be the hardest...': '您已经进行了 30 次因子提升！新的内容要来了，但最后 4 次因子提升才是最难的……',
    'Onwards!': '继续前进！',
    'You\'ve reached the current Endgame!': '您到达了目前版本的终点！',
    'AutoClickers': '自动点击器',
    'Successor AutoClicker': '后继数自动点击器',
    'Maximize AutoClicker': '最大化序数自动点击器',
    'LOCKED': '未解锁',
    'Dynamic': '动态',
    'Max All Factors [F]': '最大化所有因子[F]',
    'BuyMax AutoClickers [F]': '最大化购买自动点击器[F]',
    //#endregion
    //#region 提升器
    'Upgrades': '升级',
    'AutoBuyers': '自动购买器',
    'Challenges': '挑战',
    'Incrementy': '增量',
    'Hierarchies': '层级',
    'Overflow': '溢出',
    'Are you sure?': '您确定吗？',
    'This will reset your Booster Upgrades and return spent Boosters, but it will trigger a Booster Reset!': '这将重置您的提升器升级，返还所有提升器，但也将触发提升器重置！',
    'Go back!': '反悔取消',
    'Go ahead.': '确认继续',
    'Boosted': '提升了',
    'Refund your Booster Upgrades': '重置提升器升级',
    'This will reset your Charged Booster Upgrades and return spent Charge, but it will force you to exit your Challenge!': '这将重置您的提升器升级电荷，返还所有电荷，但也将强制您退出现在的挑战！',
    'Refund your Charged Booster Upgrades': '重置提升器升级电荷',
    'Each Factor\'s effect is doubled': '[1x1]每个因子的效果翻倍',
    '1 Boosters': '1 提升器',
    'Boost OP gain by 5x': '[1x2]使指数幂获取数量变为 5 倍',
    '5 Boosters': '5 提升器',
    'The Ordinal Base is always 5 in Challenges': '[1x3]使挑战中的序数底数常时为 5',
    '72 Boosters': '72 提升器',
    'Dynamic Gain is multiplied by your C5 completions in C1-C4': '[1x4]在挑战 1-挑战 4中使动态因子获取速度乘以挑战 5完成次数',
    '53 Boosters': '53 提升器',
    'Every 10 Darkness Upgrades purchased reduces Hierarchy Bases by 1': '[1x5]每购买 10 个黑暗升级就使层级的底数减少 1',
    '3522 Boosters': '3522 提升器',
    'Unlock Max All AutoBuyer': '[2x1]解锁最大化所有自动购买器',
    'Boosters Boost Tier 1 and 2 automation': '[2x2]使提升器可以增加自动点击器和自动购买器的效果',
    '4 Boosters': '4 提升器',
    'Gain 10x OP at Ordinal Base 5 or higher': '[2x3]当序数底数不低于 5 时，使序数幂获取数量变为 10 倍',
    '73 Boosters': '73 提升器',
    'The Ordinal Base boosts Factors (higher is better': '[2x4]使序数底数可以增加因子的效果(底数越高效果越好',
    '74 Boosters': '74 提升器',
    'Each SGH Buyable Purchased boosts the SGH Effect Exponent': '[2x5]每个慢速增长层级的升级都可以使慢速增长层级效果的指数增加',
    'Unlock Markup AutoBuyer': '[3x1]解锁增序自动购买器',
    'Gain 20 Free OP/s': '[3x2]每秒获得 20 序数幂',
    '8 Boosters': '8 提升器',
    'Gain 3 free levels of each Factor': '[3x3]每个因子免费获得 3 级',
    '16 Boosters': '16 提升器',
    'Boosters boost Dynamic gain if the Ordinal Base is less than 6': '[3x4]当序数底数低于 6 时，使提升器可以增加动态因子的获取速度',
    '66 Boosters': '66 提升器',
    'The Total ℵ effect applies to Incrementy gain': '[3x5]合计 ℵ的效果也对增量获取速度生效',
    '3562 Boosters': '3562 提升器',
    'Each Factor\'s effect is Quadrupled': '[1x1]每个因子的效果变为 4 倍',
    'Boost OP gain by 500x': '[1x2]使指数幂获取数量变为 500 倍',
    'The Ordinal Base is always 4 in Challenges': '[1x3]使挑战中的序数底数常时为 4',
    'Dynamic Gain is multiplied by your C5 completions': '[1x4]使动态因子获取速度乘以挑战 5完成次数',
    'Every 10 Darkness Upgrades or Drains purchased reduces Hierarchy Bases by 1': '[1x5]每购买 10 个黑暗升级或吸取升级就使层级的底数减少 1',
    'The AutoBuyers are boosted by Factor 7 (does not stack with Upgrade 3x1': '[2x1]使因子7可以增加自动购买器的效果(无法与升级3x1的效果同时生效',
    'Boosters Boost Tier 1 and 2 Automation at a much higher rate': '[2x2]使提升器可以更大程度地增加自动点击器和自动购买器的效果',
    'Gain 100x OP at Ordinal Base 4 or higher': '[2x3]当序数底数不低于 4 时，使序数幂获取数量变为 100 倍',
    'The Base boosts Factors but lower Base is better': '[2x4]使序数底数可以增加因子的效果，但底数越低效果越好',
    'Each SGH, FGH, and Incrementy Buyable Purchased boosts the SGH Effect Exponent': '[2x5]每个慢速增长层级、快速增长层级和增量的升级都可以使慢速增长层级效果的指数增加',
    'The AutoBuyers are boosted by Factor 7 (does not stack with Upgrade 2x1': '[3x1]使因子7可以增加自动购买器的效果(无法与升级2x1的效果同时生效',
    'Gain Free OP/s based on your Base': '[3x2]每秒获得序数幂，数量基于序数底数',
    'Gain 4 free levels of each Factor': '[3x3]每个因子免费获得 4 级',
    'Boosters boost Dynamic Gain': '[3x4]使提升器可以增加动态因子的获取速度',
    'The Total ℵ effect is multiplied by Darkness Upgrade 1 and applied to Incrementy gain': '[3x5]合计 ℵ的效果变为黑暗升级1的相应倍数，且对增量获取速度生效',
    'Unlock Challenges': '解锁挑战',
    'Requires: 6 Boosters': '需：6 提升器',
    'Unlock Incrementy': '解锁增量',
    'Requires: 91 Boosters': '需：91 提升器',
    'Unlock Hierarchies': '解锁层级',
    'Requires: 325 Boosters': '需：325 提升器',
    'Unlock Overflow': '解锁溢出',
    'Requires: 465 Boosters': '需：465 提升器',
    'Unlock Singularity, unlock Baselessness, and keep all forms of Charge on Collapse': '解锁奇点，解锁无底，坍缩时保留所有电荷',
    'Requires: 12246 Boosters': '需：12246 提升器',
    'Click a purchased Upgrade to Supercharge it!': '点击已购买的升级可以使用电荷来强化它！',
    'The Unlockables Column does not consume Boosters': '“解锁”列的升级不需要花费提升器购买',
    'Your ': '您的',
    'Max All AutoBuyer': '最大化所有自动购买器',
    'Markup AutoBuyer': '增序自动购买器',
    'Charge AutoBuyer': '电荷自动购买器',
    'RUP AutoBuyer': '增量重复升级自动购买器',
    'Hierarchy Buyable AutoBuyer': '层级升级自动购买器',
    'Booster Upgrade AutoBuyer': '提升器升级自动购买器',
    'Supercharge AutoBuyer': '电荷强化自动购买器',
    ' is clicking the Max All button ': '每秒点击最大化所有按钮 ',
    ' is clicking the Markup button ': '每秒点击增序按钮 ',
    ' is clicking the Sacrifice for Charge buttons ': '每秒点击献祭增量购买电荷按钮 ',
    ' is clicking the RUP buttons ': '每秒点击增量重复升级按钮 ',
    ' is clicking the Hierarchy Buyable buttons ': '每秒点击层级升级按钮 ',
    ' is clicking the Booster Upgrade buttons ': '每秒点击提升器升级按钮 ',
    ' is clicking the Supercharge buttons ': '每秒点击电荷强化按钮 ',
    ', but only if you can\'t Factor Shift': '，但前提条件是您无法再进行因子变换',
    ', but only if you\'re past Ψ(Ω': '，但前提条件是序数超过 Ψ(Ω',
    ', but only if you can\'t afford a Charge': '，但前提条件是您的增量不足以购买电荷',
    ', but only if you already have the required Booster Upgrade': '，但前提条件是您已经获得了对应的提升器升级',
    'You are in the Baseless Realm': '您在无底之领域',
    'You are in the Obliterated Realm': '您在消除之领域',
    'You are in the Forgotten Realm': '您在遗忘之领域',
    'Max All AutoBuyer: Enabled': '最大化所有自动购买器：启用',
    'Max All AutoBuyer: Disabled': '最大化所有自动购买器：禁用',
    'Max All AutoBuyer: LOCKED': '最大化所有自动购买器：锁定',
    'Markup AutoBuyer: Enabled': '增序自动购买器：启用',
    'Markup AutoBuyer: Disabled': '增序自动购买器：禁用',
    'Markup AutoBuyer: LOCKED': '增序自动购买器：锁定',
    'Charge AutoBuyer: Enabled': '电荷自动购买器：启用',
    'Charge AutoBuyer: Disabled': '电荷自动购买器：禁用',
    'Charge AutoBuyer: LOCKED': '电荷自动购买器：锁定',
    'RUP AutoBuyer: Enabled': '增量重复升级自动购买器：启用',
    'RUP AutoBuyer: Disabled': '增量重复升级自动购买器：禁用',
    'RUP AutoBuyer: LOCKED': '增量重复升级自动购买器：锁定',
    'Hierarchy Buyable AutoBuyer: Enabled': '层级升级自动购买器：启用',
    'Hierarchy Buyable AutoBuyer: Disabled': '层级升级自动购买器：禁用',
    'Hierarchy Buyable AutoBuyer: LOCKED': '层级升级自动购买器：锁定',
    'Booster Upgrade AutoBuyer: Enabled': '提升器升级自动购买器：启用',
    'Booster Upgrade AutoBuyer: Disabled': '提升器升级自动购买器：禁用',
    'Booster Upgrade AutoBuyer: LOCKED': '提升器升级自动购买器：锁定',
    'Supercharge AutoBuyer: Enabled': '电荷强化自动购买器：启用',
    'Supercharge AutoBuyer: Disabled': '电荷强化自动购买器：禁用',
    'Supercharge AutoBuyer: LOCKED': '电荷强化自动购买器：锁定',
    'Escape the Challenge Early': '提前退出挑战',
    'Entering a Challenge will perform a Booster Reset!': '进行挑战将同时进行一次提升器重置！',
    'No chance.': '不行。',
    'Of course!': '当然！',
    'Challenge 1': '挑战 1',
    'Challenge 2': '挑战 2',
    'Challenge 3': '挑战 3',
    'Challenge 4': '挑战 4',
    'Challenge 5': '挑战 5',
    'Challenge 6': '挑战 6',
    'Challenge 7': '挑战 7',
    'Challenge 8': '挑战 8',
    'You can only buy 1 of each AutoClicker': '您只能购买每种自动点击器各 1 次',
    'You can\'t buy Factors': '您无法购买因子',
    'The Base is 5 higher': '序数底数增加 5',
    'Factor Shifts don\'t reduce the base': '因子变换不降低序数底数',
    'Dynamic divides AutoClicker speed, and each Booster Upgrade bought and completion of this Challenge multiplies Dynamic Gain and Cap by 5': '动态因子会降低自动点击器的效果，每次购买提升器升级或完成该挑战将使动态因子获取速度和上限变为 5 倍',
    'All previous Challenges at once EXCEPT Challenge 5': '除了挑战 5以外，之前所有挑战的限制全部生效',
    'You gain no Dynamic, Booster Upgrades increase Factor Shift requirements, Booster Upgrade 1x3 is disabled, and you can only manually click Successor 1000 times per Markup': '您无法获得动态因子，购买提升器升级将增加因子变换的需求，提升器升级1x3失效，每次增序您只能手动点击 1000 次增加后继数',
    'You exponentially gain Decrementy that divides AutoClicker Speed (resets on Markup), keep no OP on Markup, and you\'re trapped in Challenge 7': '您将获得指数提升的减量，它会降低自动点击器的效果，且每次增序时重置。增序时不保留序数幂，且强制进行挑战 7',
    'Reward: Factor 1 slightly boosts Tier 2 Automation': '奖励：因子1略微增加自动购买器的效果',
    'Reward: Factor 2 slightly boosts Tier 2 Automation': '奖励：因子2略微增加自动购买器的效果',
    'Reward: Factor 3 slightly boosts Tier 2 Automation': '奖励：因子3略微增加自动购买器的效果',
    'Reward: Factor 4 slightly boosts Tier 2 Automation': '奖励：因子4略微增加自动购买器的效果',
    'Reward: Factor 5 slightly boosts Tier 2 Automation': '奖励：因子5略微增加自动购买器的效果',
    'Reward: Factor 6 slightly boosts Tier 2 Automation': '奖励：因子6略微增加自动购买器的效果',
    'Reward: Factor 7 slightly boosts Tier 2 Automation': '奖励：因子7略微增加自动购买器的效果',
    'Reward: Dynamic Factor slightly boosts Tier 2 Automation': '奖励：动态因子略微增加自动购买器的效果',
    'Forced Refund': '强制重置',
    'Your Booster Upgrades have been refunded to help with the Challenge. Feel free to rebuy them, but remember the debuff!': '为了帮助您更好地完成挑战，提升器升级已重置。',
    'You have to be in a Challenge to leave it!': '您必须在挑战中才能退出挑战！',
    'Sorry :(': '抱歉:(',
    'Leaving a Challenge early will force a Booster Reset and you will get no rewards!': '提前退出挑战将同时进行一次提升器重置，且您不会获得任何奖励！',
    'No way!': '不行！',
    'Challenge Complete!': '挑战已完成！',
    'You have Completed Challenge 1x1!': '您完成了第 1 次挑战 1！',
    'You have Completed Challenge 1x2!': '您完成了第 2 次挑战 1！',
    'You have Completed Challenge 1x3!': '您完成了第 3 次挑战 1！',
    'You have Completed Challenge 2x1!': '您完成了第 1 次挑战 2！',
    'You have Completed Challenge 2x2!': '您完成了第 2 次挑战 2！',
    'You have Completed Challenge 2x3!': '您完成了第 3 次挑战 2！',
    'You have Completed Challenge 3x1!': '您完成了第 1 次挑战 3！',
    'You have Completed Challenge 3x2!': '您完成了第 2 次挑战 3！',
    'You have Completed Challenge 3x3!': '您完成了第 3 次挑战 3！',
    'You have Completed Challenge 4x1!': '您完成了第 1 次挑战 4！',
    'You have Completed Challenge 4x2!': '您完成了第 2 次挑战 4！',
    'You have Completed Challenge 4x3!': '您完成了第 3 次挑战 4！',
    'You have Completed Challenge 5x1!': '您完成了第 1 次挑战 5！',
    'You have Completed Challenge 5x2!': '您完成了第 2 次挑战 5！',
    'You have Completed Challenge 5x3!': '您完成了第 3 次挑战 5！',
    'You have Completed Challenge 6x1!': '您完成了第 1 次挑战 6！',
    'You have Completed Challenge 6x2!': '您完成了第 2 次挑战 6！',
    'You have Completed Challenge 6x3!': '您完成了第 3 次挑战 6！',
    'You have Completed Challenge 7x1!': '您完成了第 1 次挑战 7！',
    'You have Completed Challenge 7x2!': '您完成了第 2 次挑战 7！',
    'You have Completed Challenge 7x3!': '您完成了第 3 次挑战 7！',
    'You have Completed Challenge 8x1!': '您完成了第 1 次挑战 8！',
    'You have Completed Challenge 8x2!': '您完成了第 2 次挑战 8！',
    'You have Completed Challenge 8x3!': '您完成了第 3 次挑战 8！',
    'Awesome!': '棒极了！',
    'You gain Incrementy based on your Ordinal, but only above Ψ(Ω). You cannot gain Incrementy in Challenges.': '您根据序数数量获得增量，但只有在序数超过 Ψ(Ω) 时才可以获得增量。您无法在挑战中获得增量。',
    'The first row of upgrades are re-buyable.': '第一行升级可以重复购买。',
    'Your FGH Ordinal is': '您的快速增长层级序数为',
    'Your SGH Ordinal is': '您的慢速增长层级序数为',
    'Maxed!': '已达最大！',
    'Bought!': '已购买！',
    'The Challenge Boost is Improved': '提升挑战的效果',
    'Incrementy Upgrade 6 is Improved': '提升增量升级6的效果',
    'Booster Upgrade 1x4 boosts Hierarchy Successors': '使提升器升级1x4可以增加层级的后继数增加速度',
    'If Booster Upgrades 2x1 and 3x1 are Supercharged their effects multiply each other': '如果提升器升级2x1和3x1被电荷强化了，则使它们的效果同时生效',
    'The BUP 2x1 and 3x1 effect slightly adds to the Decrementy gain exponent': '使提升器升级2x1和3x1可以略微增加减量获取数量的指数',
    'Total Charge Boosts AutoBuyers': '使电荷数量可以增加自动购买器的效果',
    'Incrementy Upgrade 2 is Improved': '提升增量升级2的效果',
    'Booster Upgrade 2x4 boosts Hierarchy Successors': '使提升器升级2x4可以增加层级的后继数增加速度',
    'Each Drain boosts the effects of the first Hierarchy Upgrade of each column': '使每个吸收升级可以增加每列第 1 个层级升级的效果',
    'The final Hierarchy Buyable of each column\'s effect adds to the ℵ': '使每列底端行的层级升级效果可以增加 ℵ',
    ' and ℵ': ' 和 ℵ',
    ' effects': '的效果',
    'Both Hierarchies are Maximized instantly. Their Successor gains are based on Incrementy Amount and AutoBuyer speed respectively.': '两种层级的序数都会直接最大化。它们的后继数增加速度分别与增量和自动购买器速度的数值有关。',
    'Multiplying the Challenge Boost to AutoBuyers by ': '使挑战对自动购买器的加成变为',
    'Multiplying Passive OP gain by ': '使序数幂的自动获取速度变为',
    'based on your total OP multiplier': '基于总序数幂倍率',
    'Dividing Decrementy Gain by ': '使减量获取速度',
    'Multiplying Decrementy Gain by ': '使减量获取速度变为',
    'Multiplying Hierarchy Successor speed by ': '使层级后继数增加速度变为',
    'Multiplying ALL Booster Power effects by ': '使所有提升器之力相关效果变为',
    'Dividing Darkness Upgrade cost exponents by ': '使黑暗升级花费的指数',
    'Multiplying the effect of the first ℵ': '使第一个ℵ',
    ' Upgrade by ': '升级的效果变为',
    'Multiplying the effect of the third bottom-row Booster Upgrade by ': '使第三个底端行的提升器升级效果变为',
    '"Excess Boosters" means all Boosters above 435': '“超额提升器”指超过 435 个以后的所有提升器',
    '"Excess Charge" means all Charge above 12': '“超额电荷”指超过 12 个以后的所有电荷',
    //#endregion
    //#region 坍缩
    'Alephs': '阿列夫升级',
    'Cardinal Upgrades': '基数升级',
    'Sluggishness': '惯性',
    'Collapse all Cardinals into random Alephs': '使所有基数随机坍缩为阿列夫升级',
    'You have ': '您拥有 ',
    'You can ': '进行',
    ' if you reach ': '需要 到达',
    ' or at any point after Factor Boost 34.': ' 或 不低于34次因子提升。',
    'You must reach Factor Boost 34 to gain any Cardinals.': '您至少需要34次因子提升才可以获得基数。',
    'Each Sluggish Milestone gives you (3*previously completed SMs) free Cardinals!': '每个惯性里程碑还可以让您获得(3×之前完成的惯性里程碑)数量的免费基数！',
    'Collapse in the required Factor Boosts or less to complete Sluggish Milestones': '在不高于相应次数因子提升的前提下进行坍缩，将可以获得相应的惯性里程碑',
    'Enter the Darkness': '进入黑暗',
    'Escape': '脱离',
    '': '',
    '': '',
    'Entering or exiting will perform a Collapse reset!': '进入或退出都将进行一次坍缩重置！',
    'Nope!': '别！',
    'Yep!': '好！',
    '': '',
    '': '',
    //#endregion
    //#region 设置
    'Consider joining ': '如果感兴趣，可以加入我们的',
    'the Discord': 'Discord频道',
    'Game': '游戏相关',
    'Confirmations': '确认弹窗',
    'UI': '游戏界面',
    'Saving': '存档相关',
    'Advanced': '高级设置',
    'Change Max Ordinal Display Length ': '调整序数最大显示长度',
    'Input New Length': '输入新的长度',
    '': '',
    'Change the Ordinal Display Mode ': '切换序数显示模式',
    '': '',
    'Change the Ordinal Color Mode ': '切换序数颜色模式',
    '': '',
    '': '',
    'Changing any of these from their default may cause lag!': '更改默认值可能会造成游戏卡顿！',
    '': '',
    'Change Millisecond Interval ': '切换毫秒时间间隔',
    'Input New Millisecond Interval (20≤x≤1000': '输入新的毫秒时间间隔(20≤x≤1000',
    'Manual Save': '手动存档',
    'Error': '错误',
    'Dang.': '该死。',
    'Export your Save': '导出存档',
    'Export Successful': '导出成功',
    'Your Data has been copied to the clipboard!': '存档数据已复制到剪贴板！',
    'Download your Save': '下载存档',
    'Success!': '下载完毕！',
    'Your save has been successfully downloaded!': '存档已下载！',
    'Import your Save': '导入存档',
    'Import SaveData': '导入存档代码',
    'Secret!': '发现隐藏秘密！',
    'You have unlocked the secret ': '您解锁了隐藏的',
    ' Ordinal Display! You can now enable or disable it in Settings :) If you\'re curious what those gwas mean check out the Info Box next to the ': '序数显示模式！您可以在设置中开启或关闭它了 :) 如果您想要知道这些表情的含义，可以查看',
    ' Display Setting!': '显示设置旁的按钮！',
    '!': '！',
    'Here\'s what those gwas mean!': '以下为表情的含义！',
    ' (aka BHO) = ': ' (及BHO) = ',
    'Thanks for the help!': '感谢！',
    'Failure': '失败',
    'No data found.': '您未输入任何内容。',
    'Oops.': '哎哟。',
    'Beta Save detected!': '检测到测试版存档！',
    'You tried to load a Beta Save into the main version. This is not allowed, sorry :(': '您尝试导入的是测试版存档。抱歉，它无法导入到正式版游戏中:(',
    'Dang it!': '该死！',
    'Delete your Save': '删除存档',
    'Are you absolutely sure you want to do this?': '您确定要这么做吗？',
    'This will export your save (just in case) but delete your save from LocalStorage.': '这将导出存档(以防万一)，然后删除您的本地存储中的游戏存档。',
    'No Way!': '不要了！',
    'Yes, I understand the consequences.': '继续，我明白。',
    'You\'re playing Ordinal Pringles v0.3.3: The World\'s Purest Pringle': '目前序数品客的版本为v0.3.3：世界上最纯正的品客',
    ' Last Update: April 2nd, 2024': '本游戏由by22dgb汉化，最后更新时间：2024年4月2日',
    //#endregion
    //#region 保持原样
    '...': '...',
    '???': '???',
    ' (3': ' (3',
    ' (4': ' (4',
    ' (5': ' (5',
    ' (6': ' (6',
    ' (7': ' (7',
    ' (8': ' (8',
    ' (9': ' (9',
    ' (10': ' (10',
    'ω': 'ω',
    'Ω': 'Ω',
    'ℵ': 'ℵ',
    'Welcome back!': 'Welcome back!',
    'New things have been added since last time': 'New things have been added since last time',
    'No!': 'No!',
    'Yes!': 'Yes!',
    'Decrementy my beloved': 'Decrementy my beloved',
    'You have Chips. In your house.': 'You have Chips. In your house.',
    'Factorial Cog': 'Factorial Cog',
    'Hello Cat': 'Hello Cat',
    'Hello MEOW': 'Hello MEOW',
    'Shifty': 'Shifty',
    'boosteeeeeeeee': 'boosteeeeeeeee',
    'boosteeeeeeeee times': 'boosteeeeeeeee times',
    'Factorial! Cog': 'Factorial! Cog',
    'Your Max All AutoBuyer is clicking the Max All button 0 times/second, but only if you can\'t Factor Shift': 'Your Max All AutoBuyer is clicking the Max All button 0 times/second, but only if you can\'t Factor Shift',
    'Your Markup AutoBuyer is clicking the Markup button 0 times/second, but only if you\'re past Ψ(Ω': 'Your Markup AutoBuyer is clicking the Markup button 0 times/second, but only if you\'re past Ψ(Ω',
    'mall Auto': 'mall Auto',
    'yes mall Auto': 'yes mall Auto',
    'fish Auto': 'fish Auto',
    'salmon\'nt Auto': 'salmon\'nt Auto',
    'salmon\'t Auto': 'salmon\'t Auto',
    'Loading...': 'Loading...',
    'Hello Dog': 'Hello Dog',
    'Jonas was here': 'Jonas was here',
    'SPEEDY QUICK': 'SPEEDY QUICK',
    'Info': 'Info',
    'slow not QUICK': 'slow not QUICK',
    'Information': 'Information',
    'boosteeeeeeeee TWO': 'boosteeeeeeeee TWO',
    'boosteeeeeeeee [POWER]': 'boosteeeeeeeee [POWER]',
    'boosteeeeeeeee TWO TWO': 'boosteeeeeeeee TWO TWO',
    'boosteeeeeeeee [POWER] TWO': 'boosteeeeeeeee [POWER] TWO',
    'Booster Power is': 'Booster Power is',
    'Overcharge is': 'Overcharge is',
    'You have Collapsed Chips. In your house.': 'You have Collapsed Chips. In your house.',
    'Total ℵ': 'Total ℵ',
    ' :': ' :',
    'Toggle Offline Progress': 'Toggle Offline Progress',
    'aaa': 'aaa',
    ' = ': ' = ',
    'Version': 'Version',
    //#endregion

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    ": ": "：",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    "Save failed.": "存档失败。",
    "Save export failed.": "存档导出失败。",
    "Save download failed.": "存档下载失败。",
    "Save import failed.": "导入存档失败。",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "：",
    "： ": "：",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?(e[+\-]?\d?\.?\d+)?(e\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^(.*)[\u4E00-\u9FFF]+(.*)$/, //不抓取内容
    /^(.*)φ(.*)$/, //不抓取内容
    /^(.*)@(.*)$/, //不抓取内容
    /^(.*)ψ(.*)$/, //不抓取内容
    /^(.*)\+[ωΩ](.*)$/, //不抓取内容
    /^[ωΩ][\d\+]+$/, //不抓取内容
    /^\d[ωΩ\d\+]+\.\.\.$/, //不抓取内容
    /^ \(\d{1,2}\)=(.*)$/, //不抓取内容
    /^\d\,?(\d\,)*\+?\d(\,\.\.\.)?$/, //不抓取内容
    /^\d\)(\(\d\))*(\(\d)?(\.\.\.)?$/, //不抓取内容
    /^\d\,\d\)(\(\d\,\d\))*(\(\d\,\d)?(\.\.\.)?$/, //不抓取内容
    /^\d\,\d\,\d\)(\(\d\,\d\,\d\))*(\(\d\,\d\,\d)?(\.\.\.)?$/, //不抓取内容
    /^[ωΩ]?(\.\.\.)?(\))+( \(I)?$/, //不抓取内容
    /^\d+[\,\.\d]+$/, //不抓取内容
    /^[\d\.e]+ 增量\n当前效果：[\d\.\,e]+ 倍$/, //不抓取内容
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
]);